// Code generated by "stringer -type BalloonEvent,IconType -output notify_string_windows.go"; DO NOT EDIT.

package windows

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BalloonShown-0]
	_ = x[BalloonClosed-1]
	_ = x[BalloonClicked-2]
}

const _BalloonEvent_name = "BalloonShownBalloonClosedBalloonClicked"

var _BalloonEvent_index = [...]uint8{0, 12, 25, 39}

func (i BalloonEvent) String() string {
	if i >= BalloonEvent(len(_BalloonEvent_index)-1) {
		return "BalloonEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BalloonEvent_name[_BalloonEvent_index[i]:_BalloonEvent_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IconNone-0]
	_ = x[IconInfo-1]
	_ = x[IconWarn-2]
	_ = x[IconError-3]
	_ = x[IconUser-4]
}

const _IconType_name = "IconNoneIconInfoIconWarnIconErrorIconUser"

var _IconType_index = [...]uint8{0, 8, 16, 24, 33, 41}

func (i IconType) String() string {
	if i >= IconType(len(_IconType_index)-1) {
		return "IconType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IconType_name[_IconType_index[i]:_IconType_index[i+1]]
}
