// Code generated by "stringer -type HashAlgorithm,Result -output gntp_string.go"; DO NOT EDIT.

package gntp

import "fmt"

const _HashAlgorithm_name = "MD5SHA1SHA256SHA512"

var _HashAlgorithm_index = [...]uint8{0, 3, 7, 13, 19}

func (i HashAlgorithm) String() string {
	if i < 0 || i >= HashAlgorithm(len(_HashAlgorithm_index)-1) {
		return fmt.Sprintf("HashAlgorithm(%d)", i)
	}
	return _HashAlgorithm_name[_HashAlgorithm_index[i]:_HashAlgorithm_index[i+1]]
}

const _Result_name = "CLICKEDCLOSEDTIMEOUT"

var _Result_index = [...]uint8{0, 7, 13, 20}

func (i Result) String() string {
	i -= 1
	if i < 0 || i >= Result(len(_Result_index)-1) {
		return fmt.Sprintf("Result(%d)", i+1)
	}
	return _Result_name[_Result_index[i]:_Result_index[i+1]]
}
